# Подписаться на пользователя
POST /users/subscriptions/1 HTTP/1.1
Host: localhost:3333
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JkYmM5ODhhZTliZGNmY2U5NGUzNTciLCJlbWFpbCI6ImZpbGlkb3JAemVsZW5peS5ydSIsImZpcnN0TmFtZSI6ItCk0LjQu9C40LTQvtGAIiwibGFzdE5hbWUiOiLQl9C10LvRkdC90YvQuSIsImlhdCI6MTY3MzM3OTAxMSwiZXhwIjoxNjczMzc5MTkxfQ.QWWvXyWnyN4bXaUlE6mpajJQvfRG_OQtoRqS1XjzGfs
Content-Type: application/json

{
  "bloggerId": "63b9e83c804280c503523c41",
  "followerId": "63b9dd9a99736fc650231e7a"
}
###

# Отписаться от пользователя
POST /users/subscriptions/0 HTTP/1.1
Host: localhost:3333
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JkYmM5ODhhZTliZGNmY2U5NGUzNTciLCJlbWFpbCI6ImZpbGlkb3JAemVsZW5peS5ydSIsImZpcnN0TmFtZSI6ItCk0LjQu9C40LTQvtGAIiwibGFzdE5hbWUiOiLQl9C10LvRkdC90YvQuSIsImlhdCI6MTY3MzM3OTAxMSwiZXhwIjoxNjczMzc5MTkxfQ.QWWvXyWnyN4bXaUlE6mpajJQvfRG_OQtoRqS1XjzGfs
Content-Type: application/json

{
  "bloggerId": "63b9e83c804280c503523c41",
  "followerId": "63b9dd9a99736fc650231e7a"
}
###
