# Создать публикацию
POST /blog/publications/ HTTP/1.1
Host: localhost:3334
Content-Type: application/json

{
  "type": "Video",
  "tags": [{ "name": "#awesomevideo"}],
  "userId": "63b550eae01809667f8f668d",
  "content": {
    "title": "Гостья из будущего",
    "videoLink": "www.url.com"
  }
}
###

# Редактировать публикацию
PATCH /blog/publications/10 HTTP/1.1
Host: localhost:3334
Content-Type: application/json
# [{ "name": "#awesomevideo"}, { "name": "#приключенияалисы"}]

{
  "type": "Video",
  "tags": [{ "name": "#awesomevideo"}, { "name": "#приключенияалисы"}],
  "content": {
    "title": "Гостья из будущего (Приключения Алисы)",
    "videoLink": "www.url.com"
  }
}
###

# Удалить публикацию
DELETE /blog/publications/4 HTTP/1.1
Host: localhost:3334
###

# Получить публикацию по ID
GET /blog/publications/11 HTTP/1.1
Host: localhost:3334
###

# Получить список публикаций (лимит, пагинация, сортировка)
GET /blog/publications/ HTTP/1.1
Host: localhost:3334
###

# Получить список публикаций определнного пользователя (лимит, пагинация, сортировка)
GET /blog/publications/user/63a9bb63c0068095cdd7706a HTTP/1.1
Host: localhost:3334
###

# Получить список черновиков публикаций пользователя (лимит, пагинация, сортировка)
GET /blog/publications/user/drafts/63a9bb63c0068095cdd7706a HTTP/1.1
Host: localhost:3334
###

# Получить список публикаций по тэгу (лимит, пагинация, сортировка)
GET /blog/publications/tag/text HTTP/1.1
Host: localhost:3334
###

# Получить ленту публикаций (лимит, пагинация, сортировка)
GET /blog/publications/feed HTTP/1.1
Host: localhost:3334
###

# Поставить лайк публикации
POST /blog/publications/like/1 HTTP/1.1
Host: localhost:3334
###

# Удалить лайк публикации
POST /blog/publications/like/0 HTTP/1.1
Host: localhost:3334
###

# Сделать репост (копировать) публикации
POST /blog/publications/repost/1 HTTP/1.1
Host: localhost:3334
###
