version: '3.9'
services:
  mongodb:
    image: mongo:latest
    container_name: course-nodejs-readme-users
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 12345
      MONGO_INITDB_DATABASE: users
    command: mongod --port 27018
    ports:
      - 27018:27018
    volumes:
      - ./db:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27018/users --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  mongodb-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345
      ME_CONFIG_MONGODB_URL: mongodb://admin:12345@mongodb:27018/
