# Создать (зарегистрировать) пользователя
POST /users/auth/register HTTP/1.1
Host: localhost:3333
Content-Type: application/json

{
  "email": "filidor@zeleniy.ru",
  "dateBirth": "1965-11-17",
  "firstName": "Филидор",
  "lastName": "Зелёный",
  "password": "123456"
}

# {
#   "email": "alisa@selezneva.ru",
#   "dateBirth": "1965-11-17",
#   "firstName": "Алиса",
#   "lastName": "Селезнева",
#   "password": "123456"
# }

# {
#   "email": "pasha@geraskin.ru",
#   "dateBirth": "1965-11-17",
#   "firstName": "Пашка",
#   "lastName": "Гераскин",
#   "password": "12345"
# }
###

# Редактировать пользователя (WIP)
PATCH  /users/auth/ HTTP/1.1
Host: localhost:3333
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JkYmM5ODhhZTliZGNmY2U5NGUzNTciLCJlbWFpbCI6ImZpbGlkb3JAemVsZW5peS5ydSIsImZpcnN0TmFtZSI6ItCk0LjQu9C40LTQvtGAIiwibGFzdE5hbWUiOiLQl9C10LvRkdC90YvQuSIsImlhdCI6MTY3MzM4MTUxNSwiZXhwIjoxNjczMzgxNjk1fQ.7X6dD_XA5TLeJWhEYrYg3ug1eLngt0ytBJkzqblmurI
Content-Type: application/json

{
  "firstName": "Filidor",
  "lastName": "Zeleniy"
}
###

# Изменить пароль пользоватьеля (WIP)
PATCH  /users/auth/pass HTTP/1.1
Host: localhost:3333
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZhbnlhM0BydXNzaWFuLnJ1IiwidXNlcklkIjoiNjJiOWY3YjI3MGY0OTZjNjczODIyNzJjIiwibmFtZSI6IlZhbnlhIFJ1c3NpYW4iLCJhdmF0YXIiOiJSTjhkOTh1NVBDbU1CZGlTREdfcGIuanBlZyIsImlhdCI6MTY1NjgzNTYxMSwiZXhwIjoxNjU2ODc4ODExfQ.YHAwjl1xwaPXpAI2dTGAw2pX3sKnEUsWyVPdUlJsTAE
Content-Type: application/json

{
  "oldPassword": "12345",
  "newPassword": "98765"
}
###

# Получить детальную информацию пользователя по ID
GET /users/auth/63a9bb63c0068095cdd7706a HTTP/1.1
Host: localhost:3333
###

# Авторизоваться (получить токен)
POST /users/auth/login HTTP/1.1
Host: localhost:3333
Content-Type: application/json

{
  "email": "filidor@zeleniy.ru",
  "password": "123456"
}
###
